networks:
  lan:

services:
  neo4jdb:
    image: neo4j:5.13
    restart: unless-stopped
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - db:/var/lib/neo4j
    networks:
      - lan
  app:
    depends_on:
      - neo4jdb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.neo4j.database" : "neo4j",
        "spring.neo4j.uri"  : "neo4j://neo4jdb:7687",
        "spring.datasource.username" : "neo4j",
        "spring.datasource.password" : "password"
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - lan
    stdin_open: true
    tty: true

volumes:
  db: